In [2]:
import numpy as np

In [3]:
mylist=[1,2,3]

In [4]:
mylist

[1, 2, 3]

In [6]:
a=np.array(mylist)

In [7]:
a

array([1, 2, 3])

In [8]:
array_2d=[[1,2,3],[4,5,6],[7,8,9]]

In [26]:
array_2d[1][0:2][0:2][0:2][1]

5

In [27]:
array_2d

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [28]:
b=np.array(array_2d)

In [29]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [33]:
#arange

In [34]:
a=np.arange(0,10)

In [35]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
a=np.arange(0,10,2)

In [38]:
a

array([0, 2, 4, 6, 8])

In [43]:
#Zeros #Ones

In [44]:
np.zeros(3)

array([0., 0., 0.])

In [45]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [47]:
#Linspace

In [58]:
np.linspace(0,10,1001)

array([ 0.  ,  0.01,  0.02, ...,  9.98,  9.99, 10.  ])

In [59]:
#eye

In [66]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [73]:
#Random Numbers [0 1] uniform random dist

In [74]:
np.random.rand(10)

array([0.95743932, 0.58197381, 0.8656398 , 0.78665075, 0.83688956,
       0.72916743, 0.24726347, 0.50156904, 0.88839768, 0.18149881])

In [80]:
np.random.randn(10)

array([ 0.0125656 , -0.78604139, -0.90718943, -0.01130647,  0.75799019,
       -0.10438585,  0.22711162, -0.97208825,  1.10133129, -0.05610571])

In [81]:
np.random.randn(10,3)

array([[-1.44532913, -1.83548645,  1.02039696],
       [ 1.79309076, -1.01044975, -0.32998553],
       [ 0.62923205,  0.60815896, -0.33322   ],
       [ 1.99489198, -0.77025239,  0.85189168],
       [-0.72780446,  1.02522032, -0.52227332],
       [-2.09181282,  0.3925607 , -2.11176093],
       [ 0.17735036, -0.69884437,  1.29474907],
       [ 0.02797992, -1.67735953, -1.70016851],
       [ 0.6665866 ,  1.51238485, -0.00482176],
       [ 1.93032918, -0.0289308 , -2.27347855]])

In [85]:
np.random.randint(1,100,10)

array([62, 24, 43, 65, 75, 42, 54, 97, 97,  8])

In [88]:
#Array Attributes

In [89]:
a=np.zeros(9)

In [90]:
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [93]:
b=a.reshape(3,3)

In [94]:
b

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [95]:
c=b.reshape(9)

In [96]:
c

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [98]:
arr=np.random.randint(1,20,9)

In [99]:
arr

array([10, 14,  3,  6,  2,  8, 19,  5,  1])

In [100]:
a=arr.reshape(3,3)

In [101]:
a

array([[10, 14,  3],
       [ 6,  2,  8],
       [19,  5,  1]])

In [102]:
a.max()

19

In [103]:
a.min()

1

In [104]:
a.argmax()

6

In [105]:
a.argmin()

8

In [107]:
a[1][1]

2

In [108]:
b=a.reshape(1,9)

In [109]:
b

array([[10, 14,  3,  6,  2,  8, 19,  5,  1]])

In [111]:
b.size

9

In [112]:
a.size

9

In [114]:
arr.size

9

In [115]:
arr.dtype

dtype('int32')

In [116]:
arr

array([10, 14,  3,  6,  2,  8, 19,  5,  1])

In [117]:
a=2*arr

In [118]:
a

array([20, 28,  6, 12,  4, 16, 38, 10,  2])

In [119]:
a=np.sqrt(arr)

In [120]:
a

array([3.16227766, 3.74165739, 1.73205081, 2.44948974, 1.41421356,
       2.82842712, 4.35889894, 2.23606798, 1.        ])

In [121]:
a=np.exp(arr)

In [122]:
a

array([2.20264658e+04, 1.20260428e+06, 2.00855369e+01, 4.03428793e+02,
       7.38905610e+00, 2.98095799e+03, 1.78482301e+08, 1.48413159e+02,
       2.71828183e+00])

In [123]:
np.sin(arr)

array([-0.54402111,  0.99060736,  0.14112001, -0.2794155 ,  0.90929743,
        0.98935825,  0.14987721, -0.95892427,  0.84147098])

In [124]:
np.log(arr)

array([2.30258509, 2.63905733, 1.09861229, 1.79175947, 0.69314718,
       2.07944154, 2.94443898, 1.60943791, 0.        ])

In [125]:
np.std(arr)

5.599823630379624

In [126]:
np.mean(arr)

7.555555555555555